services:
  - type: web
    name: pizza-manager
    env: ruby
    plan: free
    buildCommand: "bundle install && yarn install && bundle exec rake assets:precompile db:migrate"
    startCommand: "bundle exec rails s -b 0.0.0.0 -p $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pizza-manager-db
          property: connectionString
    autoDeploy: true
