

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 094e054b3e434533aeebd799b9a5580c
  host: localhost

development:
  <<: *default
  database: pizza_manager_development

test:
  <<: *default
  database: pizza_manager_test

production:
  <<: *default
  database: pizza_manager_production
  username: postgres
  password: <%= ENV['094e054b3e434533aeebd799b9a5580c'] %>
